# http://docs.travis-ci.com/user/languages/android/
language: android

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

script: gradle testDebugUnitTest